language: php
php:
  - 5.6
  - 5.5
  - 5.4
before_script:
    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mcrypt php5-intl
    - sudo sed -i -e "/DocumentRoot/i\ServerName test.dev" /etc/apache2/sites-available/default
    - echo "127.0.0.1 test.dev" | sudo tee -a /etc/hosts
    - echo "BASE_URL=test.dev/index.php" > .env
    - sudo /etc/init.d/apache2 restart
    - composer self-update
    - composer install --dev
script:
    - bin/behat
